using System;
using System.Net.Http;
using System.Text;
using System.Text.Json;
using System.Threading.Tasks;

namespace MyAIAgent.Runner.Agents
{
    public interface IModelingReviewerAgent
    {
        Task<string> ReviewAndDecorateEntityAsync(string metadataJson, string generatedCode);
    }

    public class ModelingReviewerAgent : IModelingReviewerAgent
    {
        private readonly string _apiKey;
        private readonly HttpClient _httpClient;

        public ModelingReviewerAgent(string apiKey)
        {
            _apiKey = apiKey ?? throw new ArgumentNullException(nameof(apiKey));
            _httpClient = new HttpClient();
        }

        public async Task<string> ReviewAndDecorateEntityAsync(string metadataJson, string generatedCode)
        {
            var systemPrompt = @"
You are a Senior C# Code Reviewer and Architect.
Your task is to refine a generated C# POCO Entity Class and apply company-standard EF Core DataAnnotations based on the provided JSON Metadata.

Core Constraints & Rules:
1. Compare the provided JSON metadata with the provided C# class code.
2. If the JSON shows `isKey: true`, add `[Key]`.
3. If the JSON shows `nullable: ""No""` for a string or reference type, add `[Required]` (optional if boolean, but follow conventions).
4. For the `options: ""UniqueIndex""`, you MUST add the EntityFrameworkCore `[Index(nameof(PropertyName), IsUnique = true)]` attribute AT THE TOP OF THE CLASS (Class-level attribute).
5. For the `comment` field in JSON, you MUST use the EntityFrameworkCore `[Comment(""..."")]` attribute on both the Class itself (if applicable) and on EACH Property. DO NOT use `<summary>` XML comments.
6. For the `type` field in JSON (e.g. varchar(1), nvarchar(50)), you MUST specify the DB column type using `[Column(TypeName = ""..."")]` for string types.
7. Use camelCase or exactly match the JSON property names (e.g. `id`, `type`, `name`, `url`, `enabled`) if the company standard in the example expects exact lowercase property names.
8. Output MUST include required namespaces like `using System.ComponentModel.DataAnnotations;`, `using System.ComponentModel.DataAnnotations.Schema;`, and `using Microsoft.EntityFrameworkCore;`.
9. ONLY return the final C# class code. Do not output markdown code blocks (```csharp), explanations, or thought process.
";

            // Gemini API JSON payload structure
            var requestBody = new
            {
                system_instruction = new
                {
                    parts = new[] { new { text = systemPrompt } }
                },
                contents = new[]
                {
                    new
                    {
                        parts = new[]
                        {
                            new { text = $"Here is the original JSON Metadata:\n{metadataJson}\n\nHere is the raw C# Code generated by Role A:\n{generatedCode}" }
                        }
                    }
                },
                generationConfig = new
                {
                    temperature = 0.2 // keep it deterministic
                }
            };

            var jsonPayload = JsonSerializer.Serialize(requestBody, new JsonSerializerOptions { PropertyNamingPolicy = JsonNamingPolicy.CamelCase });
            var content = new StringContent(jsonPayload, Encoding.UTF8, "application/json");

            // We use the same model version that the User changed in an earlier edit (gemini-2.5-flash)
            var url = $"https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?key={_apiKey}";
            
            var response = await _httpClient.PostAsync(url, content);
            
            if (!response.IsSuccessStatusCode)
            {
                var errorBody = await response.Content.ReadAsStringAsync();
                throw new Exception($"Gemini API Call Failed in Role B: {response.StatusCode}\n{errorBody}");
            }

            var responseBody = await response.Content.ReadAsStringAsync();
            var resultObject = JsonDocument.Parse(responseBody);
            
            try 
            {
                var generatedText = resultObject.RootElement
                                                .GetProperty("candidates")[0]
                                                .GetProperty("content")
                                                .GetProperty("parts")[0]
                                                .GetProperty("text").GetString();

                if (generatedText != null)
                {
                    generatedText = generatedText.Trim();
                    if (generatedText.StartsWith("```csharp", StringComparison.OrdinalIgnoreCase))
                    {
                        generatedText = generatedText.Substring(9);
                    }
                    else if (generatedText.StartsWith("```cs", StringComparison.OrdinalIgnoreCase))
                    {
                        generatedText = generatedText.Substring(5);
                    }
                    else if (generatedText.StartsWith("```"))
                    {
                        generatedText = generatedText.Substring(3);
                    }

                    if (generatedText.EndsWith("```"))
                    {
                        generatedText = generatedText.Substring(0, generatedText.Length - 3);
                    }

                    return generatedText.Trim();
                }
            }
            catch (Exception ex)
            {
                throw new Exception("Failed to parse the Gemini response format in Role B.", ex);
            }

            return string.Empty;
        }
    }
}
